version: '3.7'

services:
  neo4j:
    image: neo4j:5.7.0-community
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_directories_import=/
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_dbms_memory_transaction_total_max=4096MiB
      - NEO4J_server_memory_heap_max__size=4096MiB
    ports:
      - "7473:7473" # https
      - "7474:7474" # http
      - "7687:7687" # bolt

volumes:
  neo4j_data:
